# Generated by Django 3.2.7 on 2021-09-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
